# Generated by Django 3.2.5 on 2021-07-12 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='name')),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.IntegerField(max_length=10, verbose_name='phone')),
                ('language', models.CharField(max_length=250, verbose_name='language')),
                ('currency', models.CharField(max_length=10, verbose_name='currency')),
            ],
        ),
    ]
