# Generated by Django 3.2.5 on 2021-07-12 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='phone_number',
            field=models.IntegerField(verbose_name='phone'),
        ),
    ]
